version: 2.1
orbs:
  maven: circleci/maven@1.0
workflows:
  maven_test:
    jobs:
      - maven/test
steps:
  - run:
  #...
  # run tests and store XML files to a subdirectory, for example, test-results
  #...
  - store_test_results:
    path: test-results
